import oracledb
from tkinter import messagebox


class Database:
    HOST     = "localhost"
    PORT     = 1521
    SERVICE  = "XEPDB1"
    USER     = "system"
    PASSWORD = "123"

    def __init__(self):
        self.connection = None
        self.cursor = None

    def connect(self) -> bool:
        try:
            self.connection = oracledb.connect(
                user=self.USER,
                password=self.PASSWORD,
                dsn=f"{self.HOST}:{self.PORT}/{self.SERVICE}",
            )
            self.cursor = self.connection.cursor()
            return True
        except oracledb.Error as e:
            messagebox.showerror("DB Error", f"Не удалось подключиться к Oracle:\n{e}")
            return False

    def disconnect(self):
        if self.cursor:
            self.cursor.close()
        if self.connection:
            self.connection.close()

    def execute(self, sql: str, params=None) -> bool:
        try:
            self.cursor.execute(sql, params or {})
            self.connection.commit()
            return True
        except oracledb.Error as e:
            self.connection.rollback()
            messagebox.showerror("DB Error", str(e))
            return False

    def fetchall(self, sql: str, params=None) -> list:
        try:
            self.cursor.execute(sql, params or {})
            return self.cursor.fetchall()
        except oracledb.Error as e:
            messagebox.showerror("DB Error", str(e))
            return []

    def fetchone(self, sql: str, params=None):
        try:
            self.cursor.execute(sql, params or {})
            return self.cursor.fetchone()
        except oracledb.Error as e:
            messagebox.showerror("DB Error", str(e))
            return None

    def create_tables(self):
        ddl_blocks = [
            # PC_STATUS (было STATUS — зарезервировано в Oracle!)
            """
            BEGIN
              EXECUTE IMMEDIATE '
                CREATE TABLE PC_STATUS (
                  status_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  status_name VARCHAR2(50) NOT NULL
                )';
            EXCEPTION WHEN OTHERS THEN
              IF SQLCODE != -955 THEN RAISE; END IF;
            END;
            """,
            # TARIFF
            """
            BEGIN
              EXECUTE IMMEDIATE '
                CREATE TABLE TARIFF (
                  tariff_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tariff_name    VARCHAR2(100) NOT NULL,
                  price_per_hour NUMBER(10,2)  NOT NULL,
                  description    VARCHAR2(255)
                )';
            EXCEPTION WHEN OTHERS THEN
              IF SQLCODE != -955 THEN RAISE; END IF;
            END;
            """,
            # CLUB
            """
            BEGIN
              EXECUTE IMMEDIATE '
                CREATE TABLE CLUB (
                  club_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  club_name VARCHAR2(100) NOT NULL,
                  address   VARCHAR2(255),
                  phone     VARCHAR2(20)
                )';
            EXCEPTION WHEN OTHERS THEN
              IF SQLCODE != -955 THEN RAISE; END IF;
            END;
            """,
            # CLIENT
            """
            BEGIN
              EXECUTE IMMEDIATE '
                CREATE TABLE CLIENT (
                  client_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  client_name VARCHAR2(100) NOT NULL,
                  phone       VARCHAR2(20),
                  email       VARCHAR2(100)
                )';
            EXCEPTION WHEN OTHERS THEN
              IF SQLCODE != -955 THEN RAISE; END IF;
            END;
            """,
            # COMPUTER
            """
            BEGIN
              EXECUTE IMMEDIATE '
                CREATE TABLE COMPUTER (
                  computer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  pc_number   VARCHAR2(20) NOT NULL,
                  club_id     NUMBER REFERENCES CLUB(club_id),
                  status_id   NUMBER REFERENCES PC_STATUS(status_id),
                  tariff_id   NUMBER REFERENCES TARIFF(tariff_id)
                )';
            EXCEPTION WHEN OTHERS THEN
              IF SQLCODE != -955 THEN RAISE; END IF;
            END;
            """,
            # BOOKING
            """
            BEGIN
              EXECUTE IMMEDIATE '
                CREATE TABLE BOOKING (
                  booking_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  client_id   NUMBER    REFERENCES CLIENT(client_id),
                  computer_id NUMBER    REFERENCES COMPUTER(computer_id),
                  start_time  TIMESTAMP NOT NULL,
                  end_time    TIMESTAMP NOT NULL
                )';
            EXCEPTION WHEN OTHERS THEN
              IF SQLCODE != -955 THEN RAISE; END IF;
            END;
            """,
            # PAYMENT
            """
            BEGIN
              EXECUTE IMMEDIATE '
                CREATE TABLE PAYMENT (
                payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                booking_id NUMBER,
                amount NUMBER(10,2),
                payment_method VARCHAR2(50),
                payment_date DATE DEFAULT SYSDATE,
                confirmed NUMBER(1) DEFAULT 0,
                CONSTRAINT fk_payment_booking 
                FOREIGN KEY (booking_id) REFERENCES BOOKING(booking_id)
              )';
            EXCEPTION WHEN OTHERS THEN
              IF SQLCODE != -955 THEN RAISE; END IF;
            END;
            """,
        ]
        for block in ddl_blocks:
            try:
                self.cursor.execute(block)
                self.connection.commit()
            except oracledb.Error as e:
                print(f"DDL warning: {e}")

    def seed_data(self):
        row = self.fetchone("SELECT COUNT(*) FROM PC_STATUS")
        if row and row[0] > 0:
            return

        inserts = [
            "INSERT INTO PC_STATUS (status_name) VALUES ('Available')",
            "INSERT INTO PC_STATUS (status_name) VALUES ('In Use')",
            "INSERT INTO PC_STATUS (status_name) VALUES ('Maintenance')",

            "INSERT INTO TARIFF (tariff_name, price_per_hour, description) VALUES ('Standard', 300, 'Интернет и лёгкие игры')",
            "INSERT INTO TARIFF (tariff_name, price_per_hour, description) VALUES ('Gaming',   600, 'Игровые ПК высокого уровня')",
            "INSERT INTO TARIFF (tariff_name, price_per_hour, description) VALUES ('VIP',     1000, 'Отдельный бокс + премиум оборудование')",

            "INSERT INTO CLUB (club_name, address, phone) VALUES ('CyberHub Central', 'Алматы, Абая 10',       '+7 727 100-01-01')",
            "INSERT INTO CLUB (club_name, address, phone) VALUES ('GameZone North',   'Алматы, Сейфуллина 5', '+7 727 200-02-02')",

            "INSERT INTO CLIENT (client_name, phone, email) VALUES ('Айбек Джаксыбеков', '+7 701 111-11-11', 'aibek@mail.kz')",
            "INSERT INTO CLIENT (client_name, phone, email) VALUES ('Динара Сейткали',   '+7 702 222-22-22', 'dinara@mail.kz')",
            "INSERT INTO CLIENT (client_name, phone, email) VALUES ('Руслан Ахметов',    '+7 700 333-33-33', 'ruslan@gmail.com')",

            "INSERT INTO COMPUTER (pc_number, club_id, status_id, tariff_id) VALUES ('PC-01', 1, 1, 1)",
            "INSERT INTO COMPUTER (pc_number, club_id, status_id, tariff_id) VALUES ('PC-02', 1, 1, 2)",
            "INSERT INTO COMPUTER (pc_number, club_id, status_id, tariff_id) VALUES ('PC-03', 1, 3, 1)",
            "INSERT INTO COMPUTER (pc_number, club_id, status_id, tariff_id) VALUES ('PC-04', 2, 1, 2)",
            "INSERT INTO COMPUTER (pc_number, club_id, status_id, tariff_id) VALUES ('PC-05', 2, 1, 3)",
        ]
        for sql in inserts:
            self.execute(sql)
