-- DROP TABLE PAYMENT CASCADE CONSTRAINTS;
-- DROP TABLE BOOKING CASCADE CONSTRAINTS;
-- DROP TABLE COMPUTER CASCADE CONSTRAINTS;
-- DROP TABLE CLIENT CASCADE CONSTRAINTS;
-- DROP TABLE CLUB CASCADE CONSTRAINTS;
-- DROP TABLE TARIFF CASCADE CONSTRAINTS;
-- DROP TABLE PC_STATUS CASCADE CONSTRAINTS;

SELECT client_name
FROM client 
-- WHERE email LIKE '%gmail.com';